package eggy.res.strings

data object `Strings-VN` : Strings {

    override val loading: String = "Đang tải"
    override val save_image_permission_tips: String = "Chức năng lưu ảnh vô hiệu , vui lòng mở quyền hoặc cắt ảnh màn hình để lưu"
    override val get_game_info_failed: String = "Không thể lấy thông tin trò chơi"
    override val install_wechat_pls: String = "Hãy cài đặt ứng dụng Wechat trước"
    override val is_download_alipay: String = "Bạn có muốn tải và cài đặt Alipay?"
    override val is_download_wechat: String= "Bạn có muốn tải và cài đặt WeChat?"
    override val ok: String = "OK"
    override val image_save_success: String = "Lưu ảnh thành công"
    override val url_no_null: String = "URL không thể để trống"
    override val save_error_retry_pls: String = "Lưu thất bại, vui lòng thử lại"
    override val can_not_launcher_app: String = "Không thể khởi động trình"
    override val copy_qq: String = "Đã sao chép mã QQ"
    override val copy_wechat: String = "Đã sao chép mã Wechat"
    override val setting_avatar: String = "Đang cài đặt avatar"
    override val set_avatar_success: String = "Ảnh avatar cài đặt thành công"
    override val one_more_click_exit: String = "Nhấp lại lần nữa để thoát trò chơi"
    override val one_more_click_back_hall: String = "Nhấp lại lần nữa trở về Đại Sảnh"
    override val open_camera: String = "Vui lòng mở quyền truy cập album để lưu ảnh."
    override val save_image_failed: String = "Lưu ảnh thất bại, hãy kiểm tra mạng"
    override val save_qrcode_share: String = "Mã QR code đã lưu, mở Wechat sau 2s , chia sẻ cho bạn bè để cùng nhau phát tài"
    override val cancel: String = "Bỏ qua"
    override val can_not_open_file_chooser: String = "Không thể mở tệp đã chọn"
    override val upload_image_failed: String = "Lỗi không thể tải ảnh"
    override val not_support_to_pay: String = "Tạm không hỗ trợ hình thức thanh toán này"
    override val none_error: String = "Lỗi không định dạng"
    override val first_install_alipay: String = "Hãy tải ứng dụng Alipay"
    override val save_image_and_open_wechat: String = "Ảnh đã được lưu vào album, mở Wechat sau 2,5 giây."
    override val save_image_and_open_alipay: String = "Ảnh đã được lưu vào album, mở Alipay sau 2,5 giây."
    override val copy_link_and_open_wechat: String = "Đã sao chép liên kết"
    override val loading_data_do_not_close: String = "Đang tải dữ liệu, xin đừng đóng giao diện"
    override val pay_do_not_close: String = "Quầy thanh toán / Trước khi hoàn tất thanh toán xin đừng đóng giao diện"
    override val install_momo_pls: String = "Hãy tải và cài ứng dụng MoMo"
    override val install_zalo_pls: String = "Hãy tải và cài ứng dụng ZaoloPay"
    override val install_whats_app_pls: String = "Hãy tải và cài ứng dụng WhatsApp"
    override val copy_link_done: String = "Link giới thiệu đã sao chép, chia sẻ để nhận thưởng"
    override val save_image_and_open_app: String = "Ảnh lưu thành công, chia sẻ trên Zalo cho bạn bè nhận ưu đãi"
    override val done: String = "Done"
    override val next: String = "Next"
    override val search: String = "Search"
    override val go: String = "Go"
    override val send: String = "Send"
}